### ISSUE TITLE
Move this to Bitovi Academy

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/trainings#2]
Bitovi has a place where public training material is already available. We should move this content to Bitovi Academy.

**Comment by chasenlehara** [comment]
Hi Justin, this repo is just for before/after code samples and specifically _not_ any other training content or material. We’re putting the code in a public GitHub repo so we can easily make links for CodeSandbox (see the [readme](https://github.com/bitovi/trainings/blob/main/README.md)). The code in this repo is not tied to anything in Bitovi Academy, and I don’t think it will be (otherwise it would live in the Academy repo).

The way that I think about it is: we wanted a way to easily create CodeSanbox projects from source code without having to manage them in CodeSandbox. Having the code in a public repo helps us do that. While this code is public, the content is part of our private trainings and not offered for free online. Since these code samples are not part of our public Academy material, I don’t think it makes sense for them to be in that repo.

Technically, I see no reason why we couldn’t have a folder in the Academy repo with the sample code, however I don’t think that makes sense (for the reasons above). I’m going to close this issue, but please feel free to reopen it if you disagree and think these code samples need to be in the academy repo (and we will move them).

**Comment by justinbmeyer** [comment]
Why have it private? 

I think there is a case that it could provide more value overall for Bitovi being public.
